services:
  auth-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: plangen-auth-service
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    networks:
      - plangen-network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: plangen-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: plangen
    networks:
      - plangen-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: plangen-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "Harsh@3134"
    volumes:
      - redis-data:/data
    networks:
      - plangen-network

volumes:
  postgres-data:
  redis-data:

networks:
  plangen-network:
    driver: bridge
