export function getNameFromEmail(email: string) {
  const localpart = email.split("@")[0];
  const cleaned = localpart.replace(/[0-9]/g, "");
  const parts = cleaned.split(/[\.\_\-]/).filter(Boolean);
  if (parts.length > 1) {
    return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join(" ");
  }
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

export function getUsernameFromEmail(email: string) {
  const localpart = email.split("@")[0];
  const cleaned = localpart.replace(/[0-9]g/, "").toLowerCase();
  const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomDigits = Math.floor(1000 + Math.random() * 9000);
  return `${adjective}${cleaned}${randomDigits}`;
}

export const adjectives = [
  "freaky",
  "salty",
  "crazy",
  "happy",
  "sneaky",
  "lazy",
  "cool",
  "wild",
  "funky",
  "silly",
  "angry",
  "brave",
  "cheerful",
  "curious",
  "dizzy",
  "eager",
  "fancy",
  "gentle",
  "grumpy",
  "honest",
  "jolly",
  "kind",
  "lucky",
  "mighty",
  "nervous",
  "odd",
  "proud",
  "quick",
  "shy",
  "sleepy",
  "tiny",
  "vast",
  "witty",
  "zany",
  "bubbly",
  "calm",
  "daring",
  "elegant",
  "fierce",
  "glamorous",
  "hilarious",
  "innocent",
  "joyful",
  "keen",
  "lively",
  "magical",
  "noble",
  "optimistic",
  "playful",
  "quirky",
  "radical",
  "sassy",
  "trusty",
  "unique",
  "vivid",
  "wildcard",
  "youthful",
  "zealous",
  "blissful",
  "courageous",
  "dandy",
  "energetic",
  "fearless",
  "giddy",
  "humble",
  "inventive",
  "jumpy",
  "keen-eyed",
  "lighthearted",
  "mysterious",
  "naive",
  "obnoxious",
  "passionate",
  "quick-witted",
  "rebellious",
  "spunky",
  "thoughtful",
  "upbeat",
  "vivacious",
  "whimsical",
  "xenial",
  "yearning",
  "zesty",
  "adventurous",
  "bold",
  "clever",
  "determined",
  "euphoric",
  "friendly",
  "generous",
  "hopeful",
  "imaginative",
  "jovial",
  "knowledgeable",
  "luminous",
  "motivated",
  "neat",
  "optimistic",
  "polite",
  "quirky",
  "resilient",
  "spirited",
  "tenacious",
  "unusual",
  "vigilant",
  "wise",
  "yappy",
  "zephyr",
];
