import type { Template } from "./TemplatePage";

export const MOCK_TEMPLATE: Template = {
  id: "98765435678976",
  name: "AI Engineer",
  description:
    "A comprehensive 5-month roadmap to becoming an AI Engineer. Covers foundations in Math and Python, Deep Learning, MLOps, and final career preparation.",
  imageUrl:
    "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=2070&auto=format&fit=crop",
  categoryID: "3456789986543",
  tasks: [
    {
      id: "t1",
      index: 1,
      points: 100,
      task: "Math Refresher: Linear Algebra Basics",
      note: "Strong foundations lead to towering achievements.",
      dateAssigned: new Date("November 20, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t2",
      index: 2,
      points: 150,
      task: "Introduction to Machine Learning Concepts",
      note: "The seeds of knowledge planted today will grow into skills tomorrow.",
      dateAssigned: new Date("November 20, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t3",
      index: 3,
      points: 100,
      task: "Setup Development Environment for ML",
      note: "Every expert was once a beginner.",
      dateAssigned: new Date("November 20, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t4",
      index: 4,
      points: 150,
      task: "Data Visualization with Matplotlib and Seaborn",
      note: "Visualize success, then make it happen.",
      dateAssigned: new Date("November 21, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t5",
      index: 5,
      points: 150,
      task: "Data Manipulation with Pandas",
      note: "Data is the new oil, and you're learning to refine it.",
      dateAssigned: new Date("November 21, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t6",
      index: 6,
      points: 200,
      task: "Exploratory Data Analysis (EDA) Mini-Project",
      note: "Curiosity about data leads to insights others miss.",
      dateAssigned: new Date("November 22, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t7",
      index: 7,
      points: 150,
      task: "Math Refresher: Statistics and Probability",
      note: "Statistics is the grammar of data science.",
      dateAssigned: new Date("November 22, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t8",
      index: 8,
      points: 200,
      task: "Linear Regression Project: Housing Price Prediction",
      note: "Apply what you learn immediately to make it stick.",
      dateAssigned: new Date("November 23, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t9",
      index: 9,
      points: 150,
      task: "Linear Regression Theory and Implementation",
      note: "Simple models mastered deeply are more valuable than complex models understood shallowly.",
      dateAssigned: new Date("November 23, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t10",
      index: 10,
      points: 150,
      task: "Logistic Regression Theory and Implementation",
      note: "Classification problems are everywhere in AI. Master the basics first.",
      dateAssigned: new Date("November 24, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t11",
      index: 11,
      points: 150,
      task: "Logistic Regression and Classification",
      note: "Classification is about drawing boundaries—learn to draw them well.",
      dateAssigned: new Date("November 24, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t12",
      index: 12,
      points: 180,
      task: "Decision Trees and Random Forests",
      note: "Trees may bend, but forests stand strong.",
      dateAssigned: new Date("November 25, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t13",
      index: 13,
      points: 160,
      task: "Support Vector Machines (SVM)",
      note: "Find the optimal hyperplane, maximize the margin of success.",
      dateAssigned: new Date("November 26, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t14",
      index: 14,
      points: 140,
      task: "K-Nearest Neighbors and Distance Metrics",
      note: "Sometimes the answer lies in your nearest neighbors.",
      dateAssigned: new Date("November 27, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t15",
      index: 15,
      points: 150,
      task: "Naive Bayes Classifier",
      note: "Naive assumptions can lead to powerful predictions.",
      dateAssigned: new Date("November 30, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t16",
      index: 16,
      points: 170,
      task: "Model Evaluation Metrics Deep Dive",
      note: "You can't improve what you don't measure.",
      dateAssigned: new Date("December 1, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t17",
      index: 17,
      points: 180,
      task: "Cross-Validation and Hyperparameter Tuning",
      note: "Fine-tuning is the difference between good and great.",
      dateAssigned: new Date("December 2, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t18",
      index: 18,
      points: 170,
      task: "Feature Engineering Fundamentals",
      note: "Features are the fuel; algorithms are the engine.",
      dateAssigned: new Date("December 3, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t19",
      index: 19,
      points: 140,
      task: "Feature Scaling and Normalization",
      note: "Scale your features to scale your results.",
      dateAssigned: new Date("December 4, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t20",
      index: 20,
      points: 160,
      task: "Handling Missing Data and Outliers",
      note: "Clean data is the foundation of clean predictions.",
      dateAssigned: new Date("December 7, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t21",
      index: 21,
      points: 170,
      task: "Dimensionality Reduction: PCA",
      note: "Sometimes less is more—reduce dimensions, increase clarity.",
      dateAssigned: new Date("December 8, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t22",
      index: 22,
      points: 180,
      task: "Clustering: K-Means and Hierarchical",
      note: "Find the hidden patterns in the chaos.",
      dateAssigned: new Date("December 9, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t23",
      index: 23,
      points: 190,
      task: "Ensemble Methods: Bagging and Boosting",
      note: "Weak learners together create strong predictions.",
      dateAssigned: new Date("December 10, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t24",
      index: 24,
      points: 140,
      task: "Linear Algebra for ML",
      note: "Math gives you the 'why' behind the 'how'.",
      dateAssigned: new Date("December 11, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t25",
      index: 25,
      points: 200,
      task: "XGBoost and LightGBM",
      note: "Master the tools that win competitions.",
      dateAssigned: new Date("December 11, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t26",
      index: 26,
      points: 140,
      task: "Probability & Statistics Foundations",
      note: "Statistics turns data into insights.",
      dateAssigned: new Date("December 12, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t27",
      index: 27,
      points: 160,
      task: "Gradient Descent Deep Dive",
      note: "Understanding gradients means understanding learning itself.",
      dateAssigned: new Date("December 13, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t28",
      index: 28,
      points: 120,
      task: "Linear Algebra Practice",
      note: "Theory meets practice in problem-solving.",
      dateAssigned: new Date("December 14, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t29",
      index: 29,
      points: 200,
      task: "Kaggle Competition Analysis - Part 1",
      note: "Learn by doing—Kaggle is your playground.",
      dateAssigned: new Date("December 14, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t30",
      index: 30,
      points: 120,
      task: "Probability & Statistics Practice",
      note: "Statistics is your truth detector.",
      dateAssigned: new Date("December 15, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t31",
      index: 31,
      points: 200,
      task: "Kaggle Competition Analysis - Part 2",
      note: "Every submission teaches you something new.",
      dateAssigned: new Date("December 15, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t32",
      index: 32,
      points: 140,
      task: "Gradient Descent Practice",
      note: "Optimization is at the heart of learning.",
      dateAssigned: new Date("December 16, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t33",
      index: 33,
      points: 170,
      task: "Time Series Analysis Basics",
      note: "Time reveals patterns—learn to read them.",
      dateAssigned: new Date("December 16, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t34",
      index: 34,
      points: 180,
      task: "ARIMA and Forecasting Models",
      note: "Predict the future by understanding the past.",
      dateAssigned: new Date("December 17, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t35",
      index: 35,
      points: 180,
      task: "Recommendation Systems Basics",
      note: "Help users discover what they didn't know they needed.",
      dateAssigned: new Date("December 18, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t36",
      index: 36,
      points: 170,
      task: "Natural Language Processing Intro",
      note: "Language is data—learn to process it.",
      dateAssigned: new Date("December 21, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t37",
      index: 37,
      points: 180,
      task: "TF-IDF and Word Embeddings",
      note: "Words have meaning—capture it mathematically.",
      dateAssigned: new Date("December 22, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t38",
      index: 38,
      points: 200,
      task: "Sentiment Analysis Project",
      note: "Build something real—projects beat theory.",
      dateAssigned: new Date("December 23, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t39",
      index: 39,
      points: 200,
      task: "ML Project 1: House Price Prediction",
      note: "Your first real project—make it count.",
      dateAssigned: new Date("December 24, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t40",
      index: 40,
      points: 200,
      task: "ML Project 2: Customer Churn Prediction",
      note: "Solve business problems with code.",
      dateAssigned: new Date("December 25, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t41",
      index: 41,
      points: 150,
      task: "Introduction to Neural Networks",
      note: "Neural networks are the heart of modern AI—master the basics first.",
      dateAssigned: new Date("December 27, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t42",
      index: 42,
      points: 200,
      task: "ML Project 3: Credit Card Fraud Detection",
      note: "Real-world data is messy—learn to handle it.",
      dateAssigned: new Date("December 28, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t43",
      index: 43,
      points: 180,
      task: "CNNs: Convolutional Neural Networks",
      note: "CNNs revolutionized computer vision—now it's your turn to harness them.",
      dateAssigned: new Date("December 28, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t44",
      index: 44,
      points: 150,
      task: "Review and Consolidate Stage 1 Learning",
      note: "Strong foundations build tall towers.",
      dateAssigned: new Date("December 29, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t45",
      index: 45,
      points: 180,
      task: "RNNs and LSTMs: Sequential Data",
      note: "Sequential patterns are everywhere—learn to capture them.",
      dateAssigned: new Date("December 29, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t46",
      index: 46,
      points: 200,
      task: "Transformers & Attention Mechanisms",
      note: "Transformers changed everything—this is non-negotiable knowledge.",
      dateAssigned: new Date("December 30, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t47",
      index: 47,
      points: 180,
      task: "Introduction to Neural Networks (Theory)",
      note: "Welcome to deep learning—the journey begins.",
      dateAssigned: new Date("December 31, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t48",
      index: 48,
      points: 180,
      task: "PyTorch Fundamentals",
      note: "PyTorch is the industry standard—get comfortable with it.",
      dateAssigned: new Date("December 31, 2025"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t49",
      index: 49,
      points: 190,
      task: "Backpropagation and Gradient Descent",
      note: "Understand the math behind the magic.",
      dateAssigned: new Date("January 1, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t50",
      index: 50,
      points: 180,
      task: "TensorFlow & Keras Practice",
      note: "TensorFlow powers production AI at scale.",
      dateAssigned: new Date("January 1, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t51",
      index: 51,
      points: 160,
      task: "SQL for Data Engineers",
      note: "SQL is the language of data—speak it fluently.",
      dateAssigned: new Date("January 2, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t52",
      index: 52,
      points: 150,
      task: "Neural Networks Practice Day 2",
      note: "Practice makes perfect—build, break, and rebuild.",
      dateAssigned: new Date("January 3, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t53",
      index: 53,
      points: 170,
      task: "Introduction to TensorFlow and Keras",
      note: "Master the tools, master the craft.",
      dateAssigned: new Date("January 4, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t54",
      index: 54,
      points: 180,
      task: "CNNs Deep Dive Day 2",
      note: "Master the architectures that changed computer vision.",
      dateAssigned: new Date("January 4, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t55",
      index: 55,
      points: 180,
      task: "Building Multi-Layer Perceptrons (MLPs)",
      note: "Layer by layer, build intelligence.",
      dateAssigned: new Date("January 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t56",
      index: 56,
      points: 180,
      task: "CNNs Practice Day 3",
      note: "Real datasets teach you what textbooks can't.",
      dateAssigned: new Date("January 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t57",
      index: 57,
      points: 180,
      task: "RNNs and LSTMs Practice Day 2",
      note: "Sequential models unlock temporal patterns.",
      dateAssigned: new Date("January 6, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t58",
      index: 58,
      points: 150,
      task: "Activation Functions Deep Dive",
      note: "Small choices make big differences.",
      dateAssigned: new Date("January 7, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t59",
      index: 59,
      points: 200,
      task: "Transformers Deep Dive Day 2",
      note: "Build it from scratch to truly understand it.",
      dateAssigned: new Date("January 7, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t60",
      index: 60,
      points: 170,
      task: "Regularization Techniques: Dropout and Batch Normalization",
      note: "Prevent overfitting—generalize better.",
      dateAssigned: new Date("January 8, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t61",
      index: 61,
      points: 200,
      task: "Transformers Practice Day 3",
      note: "Fine-tuning turns good models into great ones.",
      dateAssigned: new Date("January 8, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t62",
      index: 62,
      points: 180,
      task: "PyTorch Practice Day 2",
      note: "Master the tools, master the craft.",
      dateAssigned: new Date("January 9, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t63",
      index: 63,
      points: 180,
      task: "TensorFlow Practice Day 2",
      note: "Production readiness starts with practice.",
      dateAssigned: new Date("January 10, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t64",
      index: 64,
      points: 170,
      task: "Optimizers: SGD, Adam, RMSprop",
      note: "Optimize your optimizer for faster learning.",
      dateAssigned: new Date("January 11, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t65",
      index: 65,
      points: 160,
      task: "SQL Practice Day 2",
      note: "SQL mastery unlocks any data source.",
      dateAssigned: new Date("January 11, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t66",
      index: 66,
      points: 180,
      task: "Introduction to Convolutional Neural Networks (CNNs)",
      note: "See the world through convolutions.",
      dateAssigned: new Date("January 12, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t67",
      index: 67,
      points: 190,
      task: "Building CNNs for Image Classification",
      note: "Train your first vision model.",
      dateAssigned: new Date("January 13, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t68",
      index: 68,
      points: 200,
      task: "Transfer Learning and Pre-trained Models",
      note: "Stand on the shoulders of giants.",
      dateAssigned: new Date("January 14, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t69",
      index: 69,
      points: 160,
      task: "Data Augmentation Techniques",
      note: "More data, better models—create it artificially.",
      dateAssigned: new Date("January 15, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t70",
      index: 70,
      points: 190,
      task: "Object Detection Basics: YOLO and R-CNN",
      note: "Detect, classify, conquer.",
      dateAssigned: new Date("January 18, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t71",
      index: 71,
      points: 190,
      task: "Image Segmentation: U-Net and Mask R-CNN",
      note: "Pixel-perfect predictions matter.",
      dateAssigned: new Date("January 19, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t72",
      index: 72,
      points: 200,
      task: "Computer Vision Project: Image Classification",
      note: "Build what others can see and use.",
      dateAssigned: new Date("January 20, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t73",
      index: 73,
      points: 180,
      task: "Introduction to Recurrent Neural Networks (RNNs)",
      note: "Time matters—model sequences intelligently.",
      dateAssigned: new Date("January 21, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t74",
      index: 74,
      points: 190,
      task: "LSTM and GRU Networks",
      note: "Remember what matters with LSTM gates.",
      dateAssigned: new Date("January 22, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t75",
      index: 75,
      points: 170,
      task: "FastAPI for Model Serving",
      note: "Models that can't be accessed are models that don't exist.",
      dateAssigned: new Date("January 25, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t76",
      index: 76,
      points: 180,
      task: "Sequence-to-Sequence Models",
      note: "Transform sequences into insights.",
      dateAssigned: new Date("January 25, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t77",
      index: 77,
      points: 190,
      task: "Attention Mechanisms",
      note: "Pay attention to what matters.",
      dateAssigned: new Date("January 26, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t78",
      index: 78,
      points: 180,
      task: "Docker Basics for ML",
      note: "Docker makes your work reproducible anywhere.",
      dateAssigned: new Date("January 26, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t79",
      index: 79,
      points: 200,
      task: "Introduction to Transformers",
      note: "The revolution in AI starts with transformers.",
      dateAssigned: new Date("January 27, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t80",
      index: 80,
      points: 170,
      task: "Streamlit/Gradio for ML Demos",
      note: "A great demo can be more impressive than perfect metrics.",
      dateAssigned: new Date("January 27, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t81",
      index: 81,
      points: 180,
      task: "CI/CD Basics for ML",
      note: "Automation separates professionals from hobbyists.",
      dateAssigned: new Date("January 28, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t82",
      index: 82,
      points: 200,
      task: "BERT and GPT Architectures",
      note: "Language models are the future—understand them deeply.",
      dateAssigned: new Date("January 28, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t83",
      index: 83,
      points: 190,
      task: "AWS Fundamentals: EC2 & S3",
      note: "Cloud skills are mandatory—AWS dominates the market.",
      dateAssigned: new Date("January 29, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t84",
      index: 84,
      points: 150,
      task: "Hugging Face Spaces Deployment",
      note: "Ship fast, iterate faster—Hugging Face makes it easy.",
      dateAssigned: new Date("January 30, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t85",
      index: 85,
      points: 150,
      task: "Render/Railway Deployment",
      note: "Multiple deployment options = more resilience.",
      dateAssigned: new Date("January 31, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t86",
      index: 86,
      points: 180,
      task: "Hugging Face Transformers Library",
      note: "Leverage the community—Hugging Face is your ally.",
      dateAssigned: new Date("February 1, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t87",
      index: 87,
      points: 170,
      task: "DVC: Data Version Control",
      note: "Version your data like you version your code.",
      dateAssigned: new Date("February 1, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t88",
      index: 88,
      points: 200,
      task: "Fine-Tuning Language Models",
      note: "Adapt giants to your needs.",
      dateAssigned: new Date("February 2, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t89",
      index: 89,
      points: 170,
      task: "MLflow: Experiment Tracking",
      note: "Track everything—your future self will thank you.",
      dateAssigned: new Date("February 2, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t90",
      index: 90,
      points: 180,
      task: "Data Pipelines Basics",
      note: "Clean pipelines prevent dirty models.",
      dateAssigned: new Date("February 3, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t91",
      index: 91,
      points: 180,
      task: "Named Entity Recognition (NER)",
      note: "Extract entities, extract value.",
      dateAssigned: new Date("February 3, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t92",
      index: 92,
      points: 170,
      task: "FastAPI Practice Day 2",
      note: "Security and monitoring are not optional.",
      dateAssigned: new Date("February 4, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t93",
      index: 93,
      points: 180,
      task: "Text Generation with GPT",
      note: "Generate intelligence, one token at a time.",
      dateAssigned: new Date("February 4, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t94",
      index: 94,
      points: 180,
      task: "Docker Practice Day 2",
      note: "Optimized containers save time and money.",
      dateAssigned: new Date("February 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t95",
      index: 95,
      points: 190,
      task: "Introduction to GANs (Generative Adversarial Networks)",
      note: "Two networks compete, one truth emerges.",
      dateAssigned: new Date("February 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t96",
      index: 96,
      points: 170,
      task: "Docker Practice Day 3",
      note: "Orchestrate containers like a symphony.",
      dateAssigned: new Date("February 6, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t97",
      index: 97,
      points: 190,
      task: "AWS Practice Day 2",
      note: "Serverless scales effortlessly.",
      dateAssigned: new Date("February 7, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t98",
      index: 98,
      points: 200,
      task: "AWS Practice Day 3",
      note: "End-to-end deployment is your superpower.",
      dateAssigned: new Date("February 8, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t99",
      index: 99,
      points: 200,
      task: "Building a Simple GAN",
      note: "Create data from noise.",
      dateAssigned: new Date("February 8, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t100",
      index: 100,
      points: 180,
      task: "Variational Autoencoders (VAEs)",
      note: "Compress and reconstruct with intelligence.",
      dateAssigned: new Date("February 9, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t101",
      index: 101,
      points: 180,
      task: "Data Pipelines Practice Day 2",
      note: "Automate the boring stuff, focus on innovation.",
      dateAssigned: new Date("February 9, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t102",
      index: 102,
      points: 180,
      task: "Reinforcement Learning Basics",
      note: "Learn through rewards and penalties.",
      dateAssigned: new Date("February 10, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t103",
      index: 103,
      points: 200,
      task: "Q-Learning and Deep Q-Networks (DQN)",
      note: "Teach machines to play and win.",
      dateAssigned: new Date("February 11, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t104",
      index: 104,
      points: 170,
      task: "Introduction to PyTorch",
      note: "Two frameworks, endless possibilities.",
      dateAssigned: new Date("February 12, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t105",
      index: 105,
      points: 180,
      task: "Model Optimization and Quantization",
      note: "Smaller models, same performance.",
      dateAssigned: new Date("February 15, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t106",
      index: 106,
      points: 200,
      task: "NLP Project: Chatbot Development",
      note: "Build intelligence that talks back.",
      dateAssigned: new Date("February 16, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t107",
      index: 107,
      points: 200,
      task: "Deep Learning Project: Image Generation with GANs",
      note: "Generate art with algorithms.",
      dateAssigned: new Date("February 17, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t108",
      index: 108,
      points: 200,
      task: "Kaggle Deep Learning Competition",
      note: "Compete globally, learn locally.",
      dateAssigned: new Date("February 18, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t109",
      index: 109,
      points: 150,
      task: "Review and Consolidate Stage 2 Learning",
      note: "Reflect, consolidate, advance.",
      dateAssigned: new Date("February 19, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t110",
      index: 110,
      points: 160,
      task: "Introduction to MLOps",
      note: "From notebooks to production.",
      dateAssigned: new Date("February 22, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t111",
      index: 111,
      points: 140,
      task: "Git and GitHub for ML Projects",
      note: "Version control your experiments.",
      dateAssigned: new Date("February 23, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t112",
      index: 112,
      points: 170,
      task: "Experiment Tracking with MLflow",
      note: "Track every experiment, waste nothing.",
      dateAssigned: new Date("February 24, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t113",
      index: 113,
      points: 160,
      task: "Model Versioning and Registry",
      note: "Version models like code.",
      dateAssigned: new Date("February 25, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t114",
      index: 114,
      points: 180,
      task: "Introduction to FastAPI",
      note: "Fast APIs for fast predictions.",
      dateAssigned: new Date("February 26, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t115",
      index: 115,
      points: 190,
      task: "Building ML Model API with FastAPI",
      note: "Make your models accessible.",
      dateAssigned: new Date("March 1, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t116",
      index: 116,
      points: 150,
      task: "API Documentation and Testing",
      note: "Good APIs are well documented.",
      dateAssigned: new Date("March 2, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t117",
      index: 117,
      points: 180,
      task: "Introduction to Docker",
      note: "Container your code, deploy anywhere.",
      dateAssigned: new Date("March 3, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t118",
      index: 118,
      points: 190,
      task: "Dockerizing ML Models",
      note: "Ship containers, not dependencies.",
      dateAssigned: new Date("March 4, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t119",
      index: 119,
      points: 170,
      task: "Docker Compose for Multi-Container Apps",
      note: "Orchestrate containers like a symphony.",
      dateAssigned: new Date("March 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t120",
      index: 120,
      points: 180,
      task: "Cloud Deployment Basics: AWS/GCP/Azure",
      note: "The cloud is your canvas.",
      dateAssigned: new Date("March 8, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t121",
      index: 121,
      points: 190,
      task: "Deploying to AWS EC2",
      note: "Deploy globally, serve millions.",
      dateAssigned: new Date("March 9, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t122",
      index: 122,
      points: 180,
      task: "Serverless Deployment with AWS Lambda",
      note: "Pay only for what you use.",
      dateAssigned: new Date("March 10, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t123",
      index: 123,
      points: 170,
      task: "Model Monitoring and Logging",
      note: "What gets monitored gets improved.",
      dateAssigned: new Date("March 11, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t124",
      index: 124,
      points: 180,
      task: "CI/CD for ML Projects",
      note: "Automate to accelerate.",
      dateAssigned: new Date("March 12, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t125",
      index: 125,
      points: 170,
      task: "Model Performance Degradation and Retraining",
      note: "Models age, but maintenance keeps them young.",
      dateAssigned: new Date("March 15, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t126",
      index: 126,
      points: 160,
      task: "A/B Testing for ML Models",
      note: "Test in production, learn in real-time.",
      dateAssigned: new Date("March 16, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t127",
      index: 127,
      points: 180,
      task: "Introduction to Kubernetes",
      note: "Scale infinitely with Kubernetes.",
      dateAssigned: new Date("March 17, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t128",
      index: 128,
      points: 190,
      task: "Data Pipeline with Apache Airflow",
      note: "Orchestrate data flows effortlessly.",
      dateAssigned: new Date("March 18, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t129",
      index: 129,
      points: 180,
      task: "Model Explainability: SHAP and LIME",
      note: "Black boxes need windows.",
      dateAssigned: new Date("March 19, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t130",
      index: 130,
      points: 170,
      task: "Bias and Fairness in ML Models",
      note: "Fair algorithms for a fair world.",
      dateAssigned: new Date("March 22, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t131",
      index: 131,
      points: 200,
      task: "MLOps Capstone Project: End-to-End Deployment",
      note: "Build a complete system—show mastery.",
      dateAssigned: new Date("March 23, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t132",
      index: 132,
      points: 150,
      task: "Review and Consolidate Stage 3 Learning",
      note: "From code to production—you're ready.",
      dateAssigned: new Date("March 24, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t133",
      index: 133,
      points: 200,
      task: "Portfolio Website Development",
      note: "Your portfolio is your billboard.",
      dateAssigned: new Date("March 25, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t134",
      index: 134,
      points: 170,
      task: "GitHub Portfolio Optimization",
      note: "Your GitHub is your resume in code.",
      dateAssigned: new Date("March 26, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t135",
      index: 135,
      points: 160,
      task: "Resume Writing for AI Engineers",
      note: "One page to tell your story.",
      dateAssigned: new Date("March 29, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t136",
      index: 136,
      points: 140,
      task: "LinkedIn Profile Optimization",
      note: "Network now, opportunities later.",
      dateAssigned: new Date("March 30, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t137",
      index: 137,
      points: 180,
      task: "Technical Blog Writing: Article 1",
      note: "Write to learn, teach to master.",
      dateAssigned: new Date("March 31, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t138",
      index: 138,
      points: 180,
      task: "Technical Blog Writing: Article 2",
      note: "Content is currency in tech.",
      dateAssigned: new Date("April 1, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t139",
      index: 139,
      points: 180,
      task: "Technical Blog Writing: Article 3",
      note: "Your voice matters—share it.",
      dateAssigned: new Date("April 2, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t140",
      index: 140,
      points: 170,
      task: "Mock Technical Interviews",
      note: "Practice makes permanent.",
      dateAssigned: new Date("April 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t141",
      index: 141,
      points: 160,
      task: "Algorithm and Data Structure Review",
      note: "Foundations matter in interviews too.",
      dateAssigned: new Date("April 6, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t142",
      index: 142,
      points: 180,
      task: "ML System Design Practice",
      note: "Design systems, architect your future.",
      dateAssigned: new Date("April 7, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t143",
      index: 143,
      points: 150,
      task: "Behavioral Interview Preparation",
      note: "Your story is your strength.",
      dateAssigned: new Date("April 8, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t144",
      index: 144,
      points: 150,
      task: "Company Research and Target List",
      note: "Know your targets, aim precisely.",
      dateAssigned: new Date("April 9, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t145",
      index: 145,
      points: 150,
      task: "Resume Optimization for AI Roles",
      note: "Your resume is your first impression—make it count.",
      dateAssigned: new Date("April 10, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t146",
      index: 146,
      points: 150,
      task: "LinkedIn Profile Polish",
      note: "LinkedIn is where opportunities find you.",
      dateAssigned: new Date("April 11, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t147",
      index: 147,
      points: 160,
      task: "GitHub Portfolio Cleanup",
      note: "Your GitHub is your technical resume—keep it pristine.",
      dateAssigned: new Date("April 12, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t148",
      index: 148,
      points: 140,
      task: "Job Application Strategy",
      note: "Strategy beats chaos every time.",
      dateAssigned: new Date("April 12, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t149",
      index: 149,
      points: 100,
      task: "Networking on LinkedIn: Week 1",
      note: "Your network is your net worth.",
      dateAssigned: new Date("April 13, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t150",
      index: 150,
      points: 180,
      task: "Job Applications: Batch 1",
      note: "Every application is a chance.",
      dateAssigned: new Date("April 14, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t151",
      index: 151,
      points: 180,
      task: "Job Applications: Batch 2",
      note: "Persistence pays off.",
      dateAssigned: new Date("April 15, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t152",
      index: 152,
      points: 180,
      task: "Technical Blog Writing: Article 4",
      note: "Keep sharing, keep growing.",
      dateAssigned: new Date("April 16, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t153",
      index: 153,
      points: 150,
      task: "Open Source Contribution: Finding Projects",
      note: "Give back to the community.",
      dateAssigned: new Date("April 19, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t154",
      index: 154,
      points: 200,
      task: "Open Source Contribution: First PR",
      note: "Contribute code, build reputation.",
      dateAssigned: new Date("April 20, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t155",
      index: 155,
      points: 100,
      task: "Networking on LinkedIn: Week 2",
      note: "Connect authentically, grow genuinely.",
      dateAssigned: new Date("April 21, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t156",
      index: 156,
      points: 180,
      task: "Job Applications: Batch 3",
      note: "Keep the momentum going.",
      dateAssigned: new Date("April 22, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t157",
      index: 157,
      points: 170,
      task: "Interview Practice: Technical Round",
      note: "Practice until you can't get it wrong.",
      dateAssigned: new Date("April 23, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t158",
      index: 158,
      points: 180,
      task: "Interview Practice: System Design Round",
      note: "Design with confidence.",
      dateAssigned: new Date("April 26, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t159",
      index: 159,
      points: 180,
      task: "Job Applications: Batch 4",
      note: "Consistency is key.",
      dateAssigned: new Date("April 27, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t160",
      index: 160,
      points: 180,
      task: "Technical Blog Writing: Article 5",
      note: "Five articles published—you're a contributor.",
      dateAssigned: new Date("April 28, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t161",
      index: 161,
      points: 150,
      task: "Networking: Coffee Chats Setup",
      note: "Learn from those ahead of you.",
      dateAssigned: new Date("April 29, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t162",
      index: 162,
      points: 160,
      task: "Salary Negotiation Preparation",
      note: "Know your worth, negotiate accordingly.",
      dateAssigned: new Date("April 30, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t163",
      index: 163,
      points: 180,
      task: "Job Applications: Batch 5",
      note: "50 applications strong—opportunities are coming.",
      dateAssigned: new Date("May 3, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t164",
      index: 164,
      points: 120,
      task: "Interview Follow-up Best Practices",
      note: "First impressions matter, last impressions linger.",
      dateAssigned: new Date("May 4, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t165",
      index: 165,
      points: 140,
      task: "Personal Branding Review",
      note: "Your brand is what they say when you're not there.",
      dateAssigned: new Date("May 5, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "t166",
      index: 166,
      points: 200,
      task: "Final Review and Celebration",
      note: "You've built the skills—now build your career!",
      dateAssigned: new Date("May 6, 2026"),
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ],
  views: 21034,
  applied: 5634,
  createdAt: new Date(),
  updatedAt: new Date(),
};
