import type { Template } from "./TemplatePage";

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "1",
    name: "Software Developer",
    description:
      "A 5-month practical roadmap to becoming a modern full-stack software developer — from TypeScript fundamentals to production-ready deployment.",
    imageUrl:
      "https://cdn.dribbble.com/userupload/44971227/file/85266d8541fa2a2cfec94c447dd1e9df.jpg?resize=1024x652&vertical=center",
    categoryID: "cat1",
    tasks: Array.from({ length: 40 }).map((_, i) => {
      const base = [
        "Learn TypeScript basics",
        "Master functions and generics",
        "Understand async/await and Promises",
        "Explore Node.js core modules",
        "Set up Express.js with TypeScript",
        "Build REST APIs with Express",
        "Add input validation using Zod",
        "Use MongoDB with Mongoose",
        "Implement authentication with JWT",
        "Understand middleware patterns",
        "Write unit tests with Jest",
        "Add logging with Winston",
        "Handle errors with a global middleware",
        "Build a simple frontend with React",
        "Connect frontend to backend via API",
        "Learn React hooks (useState, useEffect)",
        "Implement routing with React Router",
        "Use Context API for global state",
        "Style components with Tailwind CSS",
        "Add form validation with React Hook Form",
        "Integrate Redux Toolkit for state management",
        "Use Axios for API calls",
        "Learn environment configuration",
        "Implement CI/CD pipeline with GitHub Actions",
        "Write Dockerfile for your app",
        "Set up docker-compose for multi-container app",
        "Deploy app on Render or Railway",
        "Connect with PostgreSQL via Prisma",
        "Add caching with Redis",
        "Optimize queries and indexes",
        "Implement pagination and filtering",
        "Handle file uploads with Multer/S3",
        "Add role-based access control",
        "Secure app with Helmet and CORS",
        "Set up Nginx reverse proxy",
        "Add monitoring with Prometheus + Grafana",
        "Document APIs with Swagger",
        "Write integration tests",
        "Refactor and improve code quality",
        "Prepare and deploy final project",
      ];
      const t = base[i];
      return {
        id: `t${i + 1}`,
        index: i + 1,
        points: (i + 1) * 5,
        task: t,
        note: `Practical focus: ${t.toLowerCase()}`,
        dateAssigned: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    }),
    views: 21034,
    applied: 5634,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "AI Engineer",
    description:
      "End-to-end machine learning and AI engineering track — Python foundations, ML, deep learning, and deployment using modern tools.",
    imageUrl:
      "https://cdn.dribbble.com/userupload/42745249/file/original-c5a9d40f1e1ad826eea855ee2295f0e9.jpg?format=webp&resize=450x338&vertical=center",
    categoryID: "cat2",
    tasks: Array.from({ length: 40 }).map((_, i) => {
      const base = [
        "Learn Python syntax and data types",
        "Understand control flow and functions",
        "Work with Numpy arrays",
        "Explore Pandas for data manipulation",
        "Learn data visualization with Matplotlib and Seaborn",
        "Understand statistics and probability basics",
        "Clean and preprocess data",
        "Handle missing and categorical values",
        "Split datasets into train/test sets",
        "Understand linear regression",
        "Implement logistic regression",
        "Explore decision trees and random forests",
        "Learn feature scaling and normalization",
        "Understand overfitting and underfitting",
        "Implement k-means clustering",
        "Explore PCA for dimensionality reduction",
        "Use scikit-learn pipelines",
        "Train and evaluate models",
        "Understand neural networks basics",
        "Build a simple neural net with TensorFlow",
        "Use Keras Sequential API",
        "Work with activation functions",
        "Train CNN for image classification",
        "Build RNN for sequence data",
        "Handle model saving and loading",
        "Experiment with hyperparameter tuning",
        "Implement dropout and regularization",
        "Use pre-trained models (transfer learning)",
        "Understand NLP basics and tokenization",
        "Fine-tune BERT using Hugging Face",
        "Create a sentiment analysis model",
        "Build an ML pipeline with FastAPI backend",
        "Containerize model with Docker",
        "Deploy model to a cloud platform",
        "Integrate Redis caching for predictions",
        "Add request logging and metrics",
        "Monitor model performance over time",
        "Automate retraining workflow",
        "Secure API endpoints with auth",
        "Package and document final project",
      ];
      const t = base[i];
      return {
        id: `t${i + 1}`,
        index: i + 1,
        points: (i + 1) * 6,
        task: t,
        note: `Hands-on practice: ${t.toLowerCase()}`,
        dateAssigned: new Date(),
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    }),
    views: 9654,
    applied: 1243,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
